
logging:
  config: classpath:logback-dev.xml

management:
  server:
    port: 8081
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: health, metrics, heapdump, threaddump, prometheus
    jmx:
      exposure:
        exclude: '*'